version: '3.8'
services:
  web:
    build: .
    ports:
      - "5001:5000"
    environment:
      - FLASK_APP=src/flask-website/app.py
      - FLASK_RUN_HOST=0.0.0.0
      - HOSTNAME=db
      - SCHEMA=mydatabase          # Update to match your database name
      - MYSQL_USER=user            # Update to match your database user
      - MYSQL_PASSWORD=password    # Update to match your database password
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://user:password@db/mydatabase   # Update URI accordingly
      - TZ = Asia/Riyadh
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: mariadb:10.6
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword  # Update to match your root password
      - MYSQL_DATABASE=mydatabase         # Update to match your database name
      - MYSQL_USER=user                   # Update to match your database user
      - MYSQL_PASSWORD=password           # Update to match your database password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
